title = "Joe Clay"
description = """
Joe Clay's personal website, blog and portfolio. \
Features articles/tutorials about programming and music. \
"""
base_url = "https://www.seventeencups.net"
compile_sass = true
highlight_code = true
generate_rss = true

[[taxonomies]]
name = "tags"
rss = true